### ISSUE TITLE
SyntaxError with bonding_tunnel

### ISSUE THREAD

**Issue by semool** [melle/l33tport#1]
Firmware ist the newest one on Speedport Hybrid.
When i try bonding_tunnel @console it gives an error at the end so i can not pipe the output in a file.
Error message:

Unexpected token ]
SyntaxError: Unexpected token ]
    at Object.parse (native)
    at safeParse (/storage/l33tport.js:282:21)
    at /storage/l33tport.js:322:18
    at IncomingMessage.<anonymous> (/storage/l33tport.js:240:9)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:419:13)
null

**Comment by melle** [comment]
The problem is that the device is returning invalid JSON data. Sometimes it appends a comma without writing another dictionary. I found no time to implement a fix yet. A solution would be to parse the input for 

``` json
},

]
```

and remove the comma. This has to be done before the parser-call https://github.com/melle/l33tport/blob/master/l33tport.js#L159
